// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.
namespace Blackvers.Commons
{
    /// <summary>
    /// Enum representing the custom Sorting Layers in Unity.
    /// Used for 2D rendering and layer ordering.
    /// </summary>
    public enum SortingLayerName
    {
        Default = 0,
        Background = 1,
        Planets = 2,
        Miner = 3,
        Ships = 4,
        Character = 5,
    }
}
