// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.
namespace Blackvers.Commons
{
    public enum SortingLayerName
    {
        Default = 0,
        Background = 1,
        Planets = 2,
        Miner = 3,
        Ships = 4,
        Character = 5,
    }
}
