using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;
using UnityEditorInternal;
using Blackvers.Data;

namespace Blackvers.EditorTools
{
    /// <summary>
    /// Utility class to automatically generate a C# Enum based on the project's Sorting Layers.
    /// Access this tool via the 'Tools' menu in the Unity Editor.
    /// </summary>
    public static class LayerEnumGenerator
    {
        private const string FILE_PATH = "Assets/__Project/Scripts/Commons/SortingLayerName.cs";

        [MenuItem("Tools/Generate Sorting Layer Enum")]
        public static void Generate()
        {
            string[] layerNames = GetSortingLayerNames();
            string content = BuildEnumContent(layerNames);
            SaveEnumFile(content);
            
            AssetDatabase.Refresh();
            Debug.Log("<color=green>[LayerEnumGenerator]</color> Successfully generated SortingLayerName enum at: " + FILE_PATH);
        }

        [MenuItem("Tools/Fix All Planets Radius")]
        public static void FixAllPlanetsRadius()
        {
            string[] guids = AssetDatabase.FindAssets("t:PlanetData");
            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                PlanetData data = AssetDatabase.LoadAssetAtPath<PlanetData>(path);
                
                if (data == null) continue;
                
                data.radius = 0.5f;
                EditorUtility.SetDirty(data);
            }
            
            AssetDatabase.SaveAssets();
            Debug.Log("<color=green>[Fixer]</color> Successfully updated radius to 0.5 for all PlanetData assets.");
        }

        private static string[] GetSortingLayerNames()
        {
            SortingLayer[] layers = SortingLayer.layers;
            string[] names = new string[layers.Length];
            
            for (int i = 0; i < layers.Length; i++)
            {
                names[i] = layers[i].name;
            }
            
            return names;
        }

        private static string BuildEnumContent(string[] layerNames)
        {
            StringBuilder stringBuilder = new StringBuilder();
            
            stringBuilder.AppendLine("// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY.");
            stringBuilder.AppendLine("namespace Blackvers.Commons");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("    public enum SortingLayerName");
            stringBuilder.AppendLine("    {");

            for (int i = 0; i < layerNames.Length; i++)
            {
                string name = layerNames[i];
                string validName = name.Replace(" ", "");
                if (string.IsNullOrEmpty(validName)) continue;
                
                stringBuilder.AppendLine($"        {validName} = {i},");
            }

            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine("}");
            
            return stringBuilder.ToString();
        }

        private static void SaveEnumFile(string content)
        {
            string directory = Path.GetDirectoryName(FILE_PATH);
            
            // Guard Clause
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(FILE_PATH, content);
        }
    }
}
